default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: matismasters
  password: matismasters

development:
  <<: *default
  database: mrwattson_arduino_development

test:
  <<: *default
  database: mrwattson_arduino_test

production:
  <<: *default
  database: mrwattson_arduino_production
